In [1]:
import pandas as pd

In [4]:
df_analysis = pd.read_csv('analysis.csv')
df_analysis.head()

,title,maxNodes,timesteps,sizeSpike,sizeSmall,sizeRegular,dataSpike,dataSmall,dataRegular,deep,shallow,hasHighVariance,hasLowVariance
0,/home/eduardo/Desktop/new_datasets/converted/c...,115,47,True,False,False,False,False,False,False,True,False,True
1,/home/eduardo/Desktop/new_datasets/converted/c...,122,48,True,False,False,False,False,False,False,True,True,False
2,/home/eduardo/Desktop/new_datasets/converted/c...,185,58,True,False,False,True,False,False,False,True,True,False
3,/home/eduardo/Desktop/new_datasets/converted/c...,123,47,True,False,False,True,False,False,False,True,True,False
4,/home/eduardo/Desktop/new_datasets/converted/c...,57,48,True,False,False,True,False,False,False,True,True,False

In [ ]:
df_analysis['size'] =

In [5]:
df_analysis[['sizeSmall', 'sizeRegular', 'sizeSpike']]

      sizeSmall  sizeRegular  sizeSpike
0         False        False       True
1         False        False       True
2         False        False       True
3         False        False       True
4         False        False       True
5         False        False      False
6         False        False       True
7         False        False       True
8         False        False       True
9         False        False       True
10        False        False       True
11        False        False       True
12        False        False       True
13        False        False       True
14        False        False       True
15        False        False       True
16        False        False       True
17        False        False       True
18        False        False       True
19        False        False      False
20        False        False       True
21        False        False       True
22        False        False       True
23        False        False       True
24        False        False      False
25        False        False       True
26        False        False       True
27        False        False       True
28        False        False       True
29        False        False      False
...         ...          ...        ...
1475      False        False      False
1476      False        False      False
1477      False        False       True
1478      False        False       True
1479      False        False      False
1480      False        False      False
1481      False        False       True
1482      False         True      False
1483      False         True      False
1484      False        False       True
1485      False        False       True
1486      False        False       True
1487      False        False       True
1488      False        False       True
1489      False        False       True
1490      False         True      False
1491      False        False       True
1492      False        False       True
1493      False        False       True
1494      False        False       True
1495      False        False       True
1496      False        False       True
1497      False        False       True
1498      False        False       True
1499      False        False       True
1500      False        False       True
1501       True        False      False
1502       True        False      False
1503      False        False       True
1504      False        False       True

[1505 rows x 3 columns]